# Generated by Django 4.1 on 2022-08-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0002_alter_entry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['name', 'participating', 'game1', 'game2', 'game3', 'game4', 'game5', 'game6', 'game7', 'game8', 'game9', 'game10', 'game11', 'game12', 'game13', 'game14', 'game15']},
        ),
        migrations.AddField(
            model_name='entry',
            name='participating',
            field=models.BooleanField(default=False),
        ),
    ]
