# Generated by Django 4.1 on 2022-08-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0004_entry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_num', models.CharField(max_length=20)),
                ('team1', models.CharField(max_length=20)),
                ('team2', models.CharField(max_length=20)),
                ('g1_date', models.DateField(blank=True, null=True)),
                ('t1g1_score', models.CharField(max_length=20)),
                ('t2g1_score', models.CharField(max_length=20)),
                ('g2_date', models.DateField(blank=True, null=True)),
                ('t1g2_score', models.CharField(max_length=20)),
                ('t2g2_score', models.CharField(max_length=20)),
                ('g3_date', models.DateField(blank=True, null=True)),
                ('t1g3_score', models.CharField(max_length=20)),
                ('t2g3_score', models.CharField(max_length=20)),
                ('g4_date', models.DateField(blank=True, null=True)),
                ('t1g4_score', models.CharField(max_length=20)),
                ('t2g4_score', models.CharField(max_length=20)),
                ('g5_date', models.DateField(blank=True, null=True)),
                ('t1g5_score', models.CharField(max_length=20)),
                ('t2g5_score', models.CharField(max_length=20)),
                ('g6_date', models.DateField(blank=True, null=True)),
                ('t1g6_score', models.CharField(max_length=20)),
                ('t2g6_score', models.CharField(max_length=20)),
                ('g7_date', models.DateField(blank=True, null=True)),
                ('t1g7_score', models.CharField(max_length=20)),
                ('t2g7_score', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='game1',
            field=models.CharField(help_text='Winner of game 1', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='game10',
            field=models.CharField(help_text='Winner of game 10', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='game11',
            field=models.CharField(help_text='Winner of game 11', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='game12',
            field=models.CharField(help_text='Winner of game 12', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='game13',
            field=models.CharField(help_text='Winner of game 13', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='game14',
            field=models.CharField(help_text='Winner of game 14', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='game15',
            field=models.CharField(help_text='Winner of game 15', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='game2',
            field=models.CharField(help_text='Winner of game 2', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='game3',
            field=models.CharField(help_text='Winner of game 3', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='game4',
            field=models.CharField(help_text='Winner of game 4', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='game5',
            field=models.CharField(help_text='Winner of game 5', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='game6',
            field=models.CharField(help_text='Winner of game 6', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='game7',
            field=models.CharField(help_text='Winner of game 7', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='game8',
            field=models.CharField(help_text='Winner of game 8', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='game9',
            field=models.CharField(help_text='Winner of game 9', max_length=20),
        ),
    ]
