# Generated by Django 4.1 on 2022-08-13 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0005_series_alter_entry_game1_alter_entry_game10_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['name', 'participating', 'game1', 'game2', 'game3', 'game4', 'game5', 'game6', 'game7', 'game8', 'game9', 'game10', 'game11', 'game12', 'game13', 'game14', 'game15'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
    ]
