# Generated by Django 4.1 on 2022-08-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0006_alter_entry_options_alter_series_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game1', models.CharField(help_text='Winner of game 1', max_length=20)),
                ('game2', models.CharField(help_text='Winner of game 2', max_length=20)),
                ('game3', models.CharField(help_text='Winner of game 3', max_length=20)),
                ('game4', models.CharField(help_text='Winner of game 4', max_length=20)),
                ('game5', models.CharField(help_text='Winner of game 5', max_length=20)),
                ('game6', models.CharField(help_text='Winner of game 6', max_length=20)),
                ('game7', models.CharField(help_text='Winner of game 7', max_length=20)),
                ('game8', models.CharField(help_text='Winner of game 8', max_length=20)),
                ('game9', models.CharField(help_text='Winner of game 9', max_length=20)),
                ('game10', models.CharField(help_text='Winner of game 10', max_length=20)),
                ('game11', models.CharField(help_text='Winner of game 11', max_length=20)),
                ('game12', models.CharField(help_text='Winner of game 12', max_length=20)),
                ('game13', models.CharField(help_text='Winner of game 13', max_length=20)),
                ('game14', models.CharField(help_text='Winner of game 14', max_length=20)),
                ('game15', models.CharField(help_text='Winner of game 15', max_length=20)),
            ],
            options={
                'verbose_name': 'Master',
                'verbose_name_plural': 'Master',
                'ordering': ['game1', 'game2', 'game3', 'game4', 'game5', 'game6', 'game7', 'game8', 'game9', 'game10', 'game11', 'game12', 'game13', 'game14', 'game15'],
            },
        ),
    ]
