# Generated by Django 4.1 on 2022-08-15 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0008_startingteams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startingteams',
            options={'verbose_name': 'Starting Teams', 'verbose_name_plural': 'Starting Teams'},
        ),
    ]
