# Generated by Django 4.1 on 2022-08-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0009_alter_startingteams_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
