# Generated by Django 4.1 on 2022-11-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0013_alter_entry_options_alter_masterbracket_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='game_num',
            new_name='series_num',
        ),
    ]
