# Generated by Django 4.1 on 2022-11-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0014_rename_game_num_series_series_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('still_open', models.BooleanField(default=True)),
            ],
        ),
    ]
