# Generated by Django 4.1 on 2022-11-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0015_controlform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlform',
            old_name='still_open',
            new_name='activate',
        ),
    ]
