# Generated by Django 4.1 on 2022-11-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0017_rename_team1_series_awayteam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='AwayTeam',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='HomeTeam',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_num',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='t1g1_score',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='t1g2_score',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='t1g3_score',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='t1g4_score',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='t1g5_score',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='t1g6_score',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='t1g7_score',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='t2g1_score',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='t2g2_score',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='t2g3_score',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='t2g4_score',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='t2g5_score',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='t2g6_score',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='t2g7_score',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
