# Generated by Django 4.1 on 2022-11-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0018_alter_series_awayteam_alter_series_hometeam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='t1g1_score',
            new_name='AwayG1',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='t1g2_score',
            new_name='AwayG2',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='t1g3_score',
            new_name='AwayG3',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='t1g4_score',
            new_name='AwayG4',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='t1g5_score',
            new_name='AwayG5',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='t1g6_score',
            new_name='AwayG6',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='t1g7_score',
            new_name='AwayG7',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='t2g1_score',
            new_name='HomeG1',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='t2g2_score',
            new_name='HomeG2',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='t2g3_score',
            new_name='HomeG3',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='t2g4_score',
            new_name='HomeG4',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='t2g5_score',
            new_name='HomeG5',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='t2g6_score',
            new_name='HomeG6',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='t2g7_score',
            new_name='HomeG7',
        ),
        migrations.AlterField(
            model_name='series',
            name='AwayTeam',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_num',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
