# Generated by Django 4.1 on 2022-11-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0019_rename_t1g1_score_series_awayg1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='AwayTeam',
            new_name='Away',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='HomeTeam',
            new_name='Home',
        ),
    ]
