# Generated by Django 4.1 on 2022-11-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0020_rename_awayteam_series_away_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='series_num',
            new_name='num',
        ),
    ]
