# Generated by Django 4.1 on 2022-11-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0022_alter_series_away_alter_series_awayg1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
