# Generated by Django 4.1 on 2022-11-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0024_rename_is_complete_series_iscomplete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startingteams',
            name='initialize_series',
            field=models.BooleanField(default=False),
        ),
    ]
