# Generated by Django 4.1 on 2022-11-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0025_startingteams_initialize_series'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ControlForm',
            new_name='AdminControl',
        ),
        migrations.AlterModelOptions(
            name='admincontrol',
            options={'verbose_name': 'Admin Controls', 'verbose_name_plural': 'Admin Controls'},
        ),
        migrations.RenameField(
            model_name='admincontrol',
            old_name='activate',
            new_name='ActivateForm',
        ),
    ]
