# Generated by Django 4.1 on 2022-11-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0026_rename_controlform_admincontrol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admincontrol',
            old_name='ActivateForm',
            new_name='Form',
        ),
        migrations.AddField(
            model_name='admincontrol',
            name='Initialize',
            field=models.BooleanField(default=False),
        ),
    ]
