# Generated by Django 4.1 on 2022-11-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0027_rename_activateform_admincontrol_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index', models.PositiveSmallIntegerField()),
                ('Name', models.CharField(max_length=12)),
                ('MainColor', models.CharField(max_length=7)),
                ('TextColor', models.CharField(max_length=7)),
                ('IsEliminated', models.BooleanField(default=False)),
                ('RegSeasonRank', models.PositiveSmallIntegerField()),
                ('DivisionRank', models.PositiveSmallIntegerField()),
                ('initialize_series', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Starting Team',
                'verbose_name_plural': 'Starting Teams',
            },
        ),
        migrations.DeleteModel(
            name='StartingTeams',
        ),
    ]
