# Generated by Django 4.1 on 2022-11-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0029_remove_startingteam_initialize_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='series1',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='entry',
            name='series10',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='entry',
            name='series11',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='entry',
            name='series12',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='entry',
            name='series13',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='entry',
            name='series14',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='entry',
            name='series15',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='entry',
            name='series2',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='entry',
            name='series3',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='entry',
            name='series4',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='entry',
            name='series5',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='entry',
            name='series6',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='entry',
            name='series7',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='entry',
            name='series8',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='entry',
            name='series9',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='masterbracket',
            name='series1',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='masterbracket',
            name='series10',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='masterbracket',
            name='series11',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='masterbracket',
            name='series12',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='masterbracket',
            name='series13',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='masterbracket',
            name='series14',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='masterbracket',
            name='series15',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='masterbracket',
            name='series2',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='masterbracket',
            name='series3',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='masterbracket',
            name='series4',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='masterbracket',
            name='series5',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='masterbracket',
            name='series6',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='masterbracket',
            name='series7',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='masterbracket',
            name='series8',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='masterbracket',
            name='series9',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
