# Generated by Django 4.1 on 2022-11-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0034_blogpost_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='message',
            field=models.TextField(),
        ),
    ]
