# Generated by Django 4.1 on 2022-11-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0035_alter_blogpost_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='AwayTotal',
        ),
        migrations.RemoveField(
            model_name='series',
            name='HomeTotal',
        ),
        migrations.AddField(
            model_name='series',
            name='AwayWins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='HomeWins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
