# Generated by Django 4.1 on 2022-11-12 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0036_remove_series_awaytotal_remove_series_hometotal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ('num',), 'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='datetime',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 19, 23, 28, 566116), null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='Post', max_length=50),
        ),
    ]
