# Generated by Django 4.1 on 2022-11-14 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0038_entry_points_entry_tpp_masterbracket_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 11, 13, 21, 8, 50, 681036))),
                ('error', models.TextField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.RenameField(
            model_name='admincontrol',
            old_name='Initialize',
            new_name='ResetAll',
        ),
        migrations.AddField(
            model_name='admincontrol',
            name='UpdateAll',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admincontrol',
            name='Form',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 21, 8, 50, 681195), null=True),
        ),
    ]
