# Generated by Django 4.1 on 2022-11-17 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0039_consolelog_rename_initialize_admincontrol_resetall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='embedlink',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 20, 33, 20, 354815), null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='bracket/static/images/BlogPosts'),
        ),
        migrations.AlterField(
            model_name='consolelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 20, 33, 20, 354604)),
        ),
    ]
