# Generated by Django 4.1 on 2022-11-19 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0040_blogpost_embedlink_alter_blogpost_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Round1', models.CharField(max_length=20)),
                ('Round2', models.CharField(max_length=20)),
                ('Round3', models.CharField(max_length=20)),
                ('Round4', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ConsoleLog',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 16, 6, 51, 640246), null=True),
        ),
    ]
