# Generated by Django 4.1 on 2022-11-20 18:14

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0041_rounddates_delete_consolelog_alter_blogpost_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoundDates',
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-date',), 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 11, 14, 0, 136122), null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
