# Generated by Django 4.1 on 2022-11-23 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0044_alter_blogpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='AwayPreviousSeries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='HomePreviousSeries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='Loser',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='series',
            name='SeriesDep1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='SeriesDep2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='Winner',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='series',
            name='XPos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='YPos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='isMatchupSet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 14, 50, 40, 5791), null=True),
        ),
    ]
