# Generated by Django 4.1 on 2022-11-24 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0046_entry_points_potential_alter_blogpost_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='IsComplete',
            new_name='isComplete',
        ),
        migrations.RemoveField(
            model_name='series',
            name='AwayPreviousSeries',
        ),
        migrations.RemoveField(
            model_name='series',
            name='HomePreviousSeries',
        ),
        migrations.RemoveField(
            model_name='series',
            name='SeriesDep1',
        ),
        migrations.RemoveField(
            model_name='series',
            name='SeriesDep2',
        ),
        migrations.AddField(
            model_name='series',
            name='DeterminesSeries',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 19, 40, 7, 682826), null=True),
        ),
    ]
