# Generated by Django 4.1 on 2022-11-27 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0047_rename_iscomplete_series_iscomplete_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterBracket',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 14, 8, 31, 716412), null=True),
        ),
    ]
