# Generated by Django 4.1 on 2022-12-02 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0049_remove_series_ismatchupset_alter_blogpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincontrol',
            name='SeriesTracker',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 19, 2, 14, 302099), null=True),
        ),
    ]
