# Generated by Django 4.1 on 2022-12-02 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0050_admincontrol_seriestracker_alter_blogpost_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admincontrol',
            old_name='ResetAll',
            new_name='Initialize',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 19, 33, 3, 260674), null=True),
        ),
    ]
