# Generated by Django 4.1 on 2023-04-17 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0052_alter_blogpost_date_alter_blogpost_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 10, 1, 11, 849388), null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='embedlink',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
