# Generated by Django 4.1 on 2023-04-18 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0053_alter_blogpost_date_alter_blogpost_embedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 20, 43, 2, 579883), null=True),
        ),
    ]
