# Generated by Django 4.1 on 2023-04-18 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0054_blogpost_visible_alter_blogpost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 21, 2, 22, 892327), null=True),
        ),
    ]
